const reasons = [
"😊 Tu sonrisa",
"😍 Tu forma de mirarme",
"✨ Tu alegría",
"💬 Tu manera de escucharme",
"🎵 Que te intereses por mis gustos",
"💖 Tus cumplidos",
"🤝 La forma en que me apañas",
"🫂 Lo empática que eres conmigo",
"😴 Tu forma de dormir",
"🌈 Que me hables de nuestro futuro",
"💞 Todo de ti",
"😏 Tus celos",
"🔥 Sacas lo mejor de mí",
"🔐 Saber que cambiarías por mí",
"🛡️ Tu confianza",
"👫 Tu compañía",
"🧠 Tu comprensión",
"🎓 Tu educación",
"😂 Tu humor",
"🦁 Tu lealtad",
"🎙️ Tu voz",
"🌟 Eres lo mejor que me ha pasado",
"👨‍👩‍👧 Tu amor por tu familia",
"😜 Tus bromitas",
"❤️ Tu gran corazón",
"🦋 Tu valentía",
"🏡 Tu forma de ser con mi familia",
"💝 Siempre me haces sentir especial",
"⚡ Tu energía",
"👗 Tu estilo",
"🧠 Tu inteligencia",
"💬 Los apodos que me pones",
"👑 Eres la mejor",
"🫶 El apoyo que me das",
"🌸 Tu gentileza",
"🧭 Tus consejos",
"😅 Tus regaños",
"❤️ Te amo",
"💗 Te adoro",
"😁 Las sonrisas que me generas",
"🤐 Confiarme tus secretos",
"🕊️ Cómo me calmas",
"🔍 Ver cosas en mí que ni yo veo",
"🎁 Amar lo que te doy",
"🥺 Preocuparte por mí",
"🥰 Tus cachetitos",
"🤍 Lo amorosa que eres",
"📖 Cómo me sabes leer",
"🚀 Me motivas a ser mejor",
"🌙 Tu alma",
"💎 Tu desinterés material",
"🙏 Tu corazón perdonador",
"🌀 Tus defectos",
"💘 Tu amor",
"🧘 Tu madurez",
"🌺 Tu aroma",
"🌱 Me hiciste mejor persona",
"🍯 Tu alma dulce",
"🎨 Tus talentos",
"🎉 Lo extrovertida que eres",
"🌍 Eres mi mundo",
"🫀 Tu todo",
"⚖️ No me juzgas",
"💃 Tu forma de bailar",
"📝 Tus palabras",
"🎤 Tu canto",
"📞 Las llamadas antes de dormir",
"⭐ Hacerme sentir importante",
"🧠 Sabes todo de mí",
"🔄 Las oportunidades que me das",
"🛠️ Amarme con errores",
"💡 Tu luz",
"🤍 Tu cuidado",
"🧸 Tu suavidad",
"🎯 Tu dedicación",
"🔎 Tu enfoque",
"🤝 Tu consideración",
"🌹 Tu presencia",
"🚴 Tu motivación",
"😤 Tus berrinches",
"🔥 Tu calidez",
"👀 Tus ojos",
"💇 Tu pelo liso",
"🏊 Tu pelo mojado",
"🌊 Tu pelo ondulado",
"😁 Tus dientes",
"👃 Tu nariz perfecta",
"🌺 Lo preciosa que eres",
"💓 Cómo me tienes enamorado",
"🤓 Cómo te ves con lentes",
"👚 Cómo te vistes",
"💋 Tus labios",
"🤎 Lo morenita que eres",
"🌼 Bonita",
"🌷 Guapa",
"🌹 Hermosa",
"😊 Tu carita",
"🎶 Las canciones que me dedicas",
"🦄 Lo única que eres",
"✨ Tu hermosura",
"🍭 Tu dulzura",
"🎭 Tu personalidad",
"💍 Tu dedicación a nosotros",
"🔓 Mostrarme tu ser",
"⏳ Tu paciencia",
"🗣️ Tu sinceridad",
"🤝 Tu respeto",
"🧸 Tu ternura",
"💞 Tu sensibilidad",
"🏋️ Tu fortaleza",
"🌾 Tu humildad",
"🤗 Porque eres cariñosa",
"🎮 Porque juegas conmigo",
"❤️ Porque te amo mucho",
"👧 Porque eres mi niña",
"🌅 Tu sonrisa al despertar",
"🤍 Tu forma de abrazar",
"💋 Tus besos",
"🤣 Tu risa",
"🥺 Tu mirada cuando me extrañas",
"🛡️ Tu apoyo incondicional",
"🕊️ Tu perdón",
"📜 Tu honestidad",
"👼 Tu nobleza",
"📆 Tu cariño diario",
"🎧 Tu voz diciendo te amo",
"🌙 Tu compañía en silencio",
"🫶 Tu forma de cuidarme",
"💓 Demostrar amor",
"🤲 Tu entrega",
"💍 Porque eres mi esposa",
"👯 Porque eres mi mejor amiga",
"🧠 Porque eres mi psicóloga",
"📚 Porque eres mi profesora",
"🏠 Porque eres mi refugio",
"👂 Escucharme siempre",
"🛡️ Protegerme",
"🎯 Apoyar mis metas",
"🎉 Tu entusiasmo",
"🎈 Tu espontaneidad",
"🗨️ Tu sinceridad al hablar",
"🤝 Aprender juntos",
"📜 Tu compromiso",
"💞 Amar sin miedo",
"🦁 Lealtad en lo difícil",
"🌧️ Sonreír en mis peores días",
"🤍 Cuidarme tanto",
"😅 Regañarme",
"📲 Estar pendiente",
"🌈 Darme ánimo",
"💓 Cariño constante",
"📆 Dedicación diaria",
"❤️ Amor verdadero",
"🛡️ Cuidarnos",
"🧠 Comprender mis errores",
"😄 Alegría compartida",
"🔐 Confiar en mí",
"⏰ Esperarme",
"💭 Sinceridad emocional",
"🛟 Apoyarme cuando caigo",
"🚀 Motivarme",
"📍 Estar incluso lejos",
"🎉 Celebrar lo simple",
"🗣️ Tu ternura al hablar",
"🤍 Amar a otros",
"💎 Tu corazón limpio",
"🕊️ Perdonar",
"🌸 Tu sensibilidad",
"🌾 Tu humildad",
"📖 Enseñarme",
"🛡️ Cuidado constante",
"♾️ Amor sin condiciones",
"🙏 Fe en nosotros",
"💪 Fortaleza emocional",
"👂 Saber escuchar",
"🤍 Sinceridad conmigo",
"🔒 Confiar",
"💖 Cariño eterno",
"🌙 Dedicación silenciosa",
"♾️ Paciencia infinita",
"😁 Sonrisa sincera",
"📆 Amor diario",
"🫂 Abrazar mi alma",
"🚶 Acompañarme",
"🧠 Comprensión profunda",
"🛡️ Proteger nuestro amor",
"🔁 Constancia",
"🤝 Apoyo sincero",
"💓 Cuidar mi corazón",
"🦢 Amor fiel",
"🌸 Ternura constante",
"🤍 Respeto mutuo",
"🔥 Dedicación total",
"💖 Amar con el alma",
"🌙 Tu presencia que calma",
"✨ Tu luz en mi vida",
"❤️ Tu amor verdadero",
"💍 Elegirme cada día",
"🙏 Porque quiero toda una vida contigo, con la bendición de Dios"
];
